### ISSUE TITLE
Hovering car

### ISSUE THREAD

**Issue by wywhynot** [JHDane/10-Years-Later#1]
I've only just started using the mod and it is so great, I love it! The flooding is a good feature addition, makes things interesting if zombies chase me and I see one ahead. Would be nice if we could slowly wade through it though. The issue: i encountered is a floating car, hovering above a flooded area and a mailbox

**Comment by JHDane** [comment]
Hey, Flying cars are linked to the placement of trees, it would be necessary to redo all the parkingstall in mapping which is not planned.
